// src/utils/pdfGenerator.ts
import jsPDF from 'jspdf';

interface PatientData {
  name: string;
  age: string;
  sex: string;
  caseHistory: string;
  symptoms: string;
  referringDoctor: string;
}

interface GeneratePDFOptions {
  report: string;
  image?: File;
  patientData?: PatientData;
  doctorName?: string;
}

export const generateMedicalReportPDF = async (options: GeneratePDFOptions): Promise<void> => {
  const { report, image, patientData, doctorName = "Dr. Medical AI" } = options;

  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;

  // Helper function to add text with word wrapping
  const addWrappedText = (text: string, x: number, y: number, maxWidth: number, lineHeight: number = 6) => {
    const lines = pdf.splitTextToSize(text, maxWidth);
    lines.forEach((line: string, index: number) => {
      if (y + (index * lineHeight) > pageHeight - margin) {
        pdf.addPage();
        y = margin;
      }
      pdf.text(line, x, y + (index * lineHeight));
    });
    return y + (lines.length * lineHeight);
  };

  // Header
  pdf.setFontSize(22);
  pdf.setFont("helvetica", "bold");
  pdf.text("MEDICAL X-RAY REPORT", pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 8;

  // Subtitle
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "italic");
  pdf.setTextColor(100, 100, 100);
  pdf.text("AI-Powered Medical Image Analysis", pageWidth / 2, yPosition, { align: 'center' });
  pdf.setTextColor(0, 0, 0);
  yPosition += 10;

  // Divider line
  pdf.setLineWidth(0.5);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 12;

  // Date and Report Information
  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  pdf.setFont("helvetica", "bold");
  pdf.text("Report Date:", margin, yPosition);
  pdf.setFont("helvetica", "normal");
  pdf.text(currentDate, margin + 35, yPosition);
  yPosition += 7;

  pdf.setFont("helvetica", "bold");
  pdf.text("Generated By:", margin, yPosition);
  pdf.setFont("helvetica", "normal");
  pdf.text(doctorName, margin + 35, yPosition);
  yPosition += 10;

  // Patient Information Section
  if (patientData && (patientData.name || patientData.age || patientData.sex)) {
    pdf.setLineWidth(0.3);
    pdf.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 8;

    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.text("PATIENT INFORMATION", margin, yPosition);
    yPosition += 10;

    pdf.setFontSize(11);
    if (patientData.name) {
      pdf.setFont("helvetica", "bold");
      pdf.text("Name:", margin, yPosition);
      pdf.setFont("helvetica", "normal");
      pdf.text(patientData.name, margin + 35, yPosition);
      yPosition += 7;
    }

    if (patientData.age || patientData.sex) {
      const ageText = patientData.age ? `${patientData.age} years` : 'N/A';
      const sexText = patientData.sex || 'N/A';

      pdf.setFont("helvetica", "bold");
      pdf.text("Age:", margin, yPosition);
      pdf.setFont("helvetica", "normal");
      pdf.text(ageText, margin + 35, yPosition);

      pdf.setFont("helvetica", "bold");
      pdf.text("Sex:", margin + 80, yPosition);
      pdf.setFont("helvetica", "normal");
      pdf.text(sexText, margin + 95, yPosition);
      yPosition += 7;
    }

    if (patientData.referringDoctor) {
      pdf.setFont("helvetica", "bold");
      pdf.text("Referring Doctor:", margin, yPosition);
      pdf.setFont("helvetica", "normal");
      pdf.text(patientData.referringDoctor, margin + 40, yPosition);
      yPosition += 7;
    }

    if (patientData.symptoms) {
      pdf.setFont("helvetica", "bold");
      pdf.text("Symptoms:", margin, yPosition);
      yPosition += 6;
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(10);
      const maxWidth = pageWidth - (2 * margin);
      yPosition = addWrappedText(patientData.symptoms, margin + 5, yPosition, maxWidth - 5, 5);
      yPosition += 2;
    }

    if (patientData.caseHistory) {
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      pdf.text("Medical History:", margin, yPosition);
      yPosition += 6;
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(10);
      const maxWidth = pageWidth - (2 * margin);
      yPosition = addWrappedText(patientData.caseHistory, margin + 5, yPosition, maxWidth - 5, 5);
      yPosition += 2;
    }

    yPosition += 8;
  }

  // Add image if provided
  if (image) {
    try {
      // Check if we need a new page
      if (yPosition > pageHeight - 100) {
        pdf.addPage();
        yPosition = margin;
      }

      pdf.setLineWidth(0.3);
      pdf.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 8;

      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");
      pdf.text("X-RAY IMAGE", margin, yPosition);
      yPosition += 10;

      const imageDataUrl = await fileToDataUrl(image);
      const imgWidth = 100;
      const imgHeight = 75;

      // Center the image
      const imgX = (pageWidth - imgWidth) / 2;

      // Add a border around the image
      pdf.setDrawColor(200, 200, 200);
      pdf.setLineWidth(0.5);
      pdf.rect(imgX - 2, yPosition - 2, imgWidth + 4, imgHeight + 4);

      pdf.addImage(imageDataUrl, 'JPEG', imgX, yPosition, imgWidth, imgHeight);
      yPosition += imgHeight + 12;

      pdf.setFontSize(9);
      pdf.setFont("helvetica", "italic");
      pdf.setTextColor(100, 100, 100);
      pdf.text("Figure: Uploaded X-Ray Image", pageWidth / 2, yPosition, { align: 'center' });
      pdf.setTextColor(0, 0, 0);
      yPosition += 12;
    } catch (error) {
      console.warn('Could not add image to PDF:', error);
    }
  }

  // Check if we need a new page for the report
  if (yPosition > pageHeight - 80) {
    pdf.addPage();
    yPosition = margin;
  }

  // AI Analysis Report Section
  pdf.setLineWidth(0.3);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 8;

  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text("AI ANALYSIS REPORT", margin, yPosition);
  yPosition += 10;

  // Report content
  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");
  const maxTextWidth = pageWidth - (2 * margin);
  yPosition = addWrappedText(report, margin, yPosition, maxTextWidth, 6);

  // Footer
  yPosition += 15;
  if (yPosition > pageHeight - 40) {
    pdf.addPage();
    yPosition = margin;
  }

  pdf.setLineWidth(0.3);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 8;

  pdf.setFontSize(8);
  pdf.setFont("helvetica", "italic");
  pdf.setTextColor(80, 80, 80);
  pdf.text("DISCLAIMER", margin, yPosition);
  yPosition += 5;
  pdf.text("This report was generated using AI-powered medical image analysis technology.", margin, yPosition);
  yPosition += 4;
  pdf.text("This is NOT a substitute for professional medical diagnosis. Please consult a qualified healthcare provider.", margin, yPosition);
  pdf.setTextColor(0, 0, 0);

  // Add page number
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
  }

  // Generate filename with patient name if available
  const timestamp = new Date().toISOString().slice(0, 19).replace(/:/g, '-');
  const patientNamePart = patientData?.name
    ? patientData.name.replace(/\s+/g, '-').toLowerCase()
    : 'patient';
  const filename = `xray-report-${patientNamePart}-${timestamp}.pdf`;

  // Download the PDF
  pdf.save(filename);
};

// Helper function to convert File to data URL
const fileToDataUrl = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
};