// src/utils/pdfGenerator.ts
import jsPDF from 'jspdf';

interface GeneratePDFOptions {
  report: string;
  image?: File;
  patientName?: string;
  doctorName?: string;
}

export const generateMedicalReportPDF = async (options: GeneratePDFOptions): Promise<void> => {
  const { report, image, patientName = "Patient", doctorName = "Dr. Medical AI" } = options;
  
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;

  // Helper function to add text with word wrapping
  const addWrappedText = (text: string, x: number, y: number, maxWidth: number, lineHeight: number = 6) => {
    const lines = pdf.splitTextToSize(text, maxWidth);
    lines.forEach((line: string, index: number) => {
      if (y + (index * lineHeight) > pageHeight - margin) {
        pdf.addPage();
        y = margin;
      }
      pdf.text(line, x, y + (index * lineHeight));
    });
    return y + (lines.length * lineHeight);
  };

  // Header
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.text("MEDICAL REPORT", pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Divider line
  pdf.setLineWidth(0.5);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 15;

  // Date and Patient Information
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  
  pdf.text(`Date: ${currentDate}`, margin, yPosition);
  yPosition += 8;
  pdf.text(`Patient: ${patientName}`, margin, yPosition);
  yPosition += 8;
  pdf.text(`Report Generated By: ${doctorName}`, margin, yPosition);
  yPosition += 15;

  // Add image if provided
  if (image) {
    try {
      const imageDataUrl = await fileToDataUrl(image);
      const imgWidth = 80;
      const imgHeight = 60;
      
      // Center the image
      const imgX = (pageWidth - imgWidth) / 2;
      
      pdf.addImage(imageDataUrl, 'JPEG', imgX, yPosition, imgWidth, imgHeight);
      yPosition += imgHeight + 15;
      
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "italic");
      pdf.text("Medical Image", pageWidth / 2, yPosition, { align: 'center' });
      yPosition += 15;
    } catch (error) {
      console.warn('Could not add image to PDF:', error);
    }
  }

  // Report Section
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text("ANALYSIS REPORT", margin, yPosition);
  yPosition += 10;

  // Divider line
  pdf.setLineWidth(0.3);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Report content
  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");
  const maxTextWidth = pageWidth - (2 * margin);
  yPosition = addWrappedText(report, margin, yPosition, maxTextWidth);

  // Footer
  yPosition = pageHeight - 30;
  pdf.setLineWidth(0.3);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;
  
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "italic");
  pdf.text("This report was generated using AI-powered medical image analysis.", margin, yPosition);
  pdf.text("Please consult with a qualified medical professional for diagnosis and treatment.", margin, yPosition + 5);
  
  // Add page number
  pdf.text(`Page 1 of 1`, pageWidth - margin, yPosition, { align: 'right' });

  // Generate filename with timestamp
  const timestamp = new Date().toISOString().slice(0, 19).replace(/:/g, '-');
  const filename = `medical-report-${timestamp}.pdf`;

  // Download the PDF
  pdf.save(filename);
};

// Helper function to convert File to data URL
const fileToDataUrl = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
};